url: https://zhanweimin2021.github.io

title: 植物基因表达调控及豆科植物发育

keywords: 植物基因表达调控及豆科植物发育

description: 植物基因表达调控及豆科植物发育

address: 广东省广州市大学城外环西路230号广州大学生命科学学院生化实验楼536

contacts: 董志诚教授

email: zc_dong@gzhu.edu.cn

exclude:
  - README.md
